### ISSUE TITLE
Autoready bug

### ISSUE THREAD

**Issue by CampaUTN** [gamersclub-booster/gamersclub-booster#76] opened 2021-06-04 04:38 UTC
Since Gamers Club UI got updated, auto ready sometimes wont work
I cannot reproduce it, but I think it happens when the tab is not open

**Comment by henriquelbsouza** [comment] 2021-06-04 12:21
Hi, the issue seems to be related to some kind of "stand by" on tabs due to the browsers config. I am not able to reproduce and we are still trying to figure this out. We already tried using a timer that clicks on "Ready" every 100ms and also by using an Observer that checks every change in the body until the Ready button appears, and then click on it.

Both works for me, and both were used in the old layout. I will keep seeking for a solution to those odd cases. 

If you have any knwoledge or any other ideas, please let us know.

Can you share your specs? Browser, version, premium/free account, pc specs, etc? Since I cannot reproduce, I am trying to figure this out.

**Comment by CampaUTN** [comment] 2021-06-04 20:13
Of course, if I have any idea I will share it to you, great plugin btw and thanks for doing this!

Specs: Chrome Versión 91.0.4472.77 (Build oficial) (64 bits). Windows 10 21H1. Gamersclub Plus account

This chrome version is very recently 25/5 ([details](https://en.wikipedia.org/wiki/Google_Chrome_version_history))
I will ask my teammates which version do they have. If someone have any older version and the autoready wont work, it should be something from the new UI

**Comment by henriquelbsouza** [comment] 2021-06-05 03:46
I just sent an update tha try 2 different clicks on the Ready button. Maybe it fixes, maybe it doesn't... If you can try it out it is 2.3.9

**Comment by henriquelbsouza** [comment] 2021-06-07 16:41
@CampaUTN are you still having issues? Can I close this thread?

**Comment by CampaUTN** [comment] 2021-06-07 20:03
Haven't played too much to fully test it but last matches worked perfectly! Thanks!

**Comment by henriquelbsouza** [comment] 2021-06-16 13:47
I will assume it is fixed for now. Thanks for the report.

**Closed by henriquelbsouza** 2021-06-16 13:47 UTC
